name: Build and Publish NPM Package

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: npm install

      - name: Add @sepior/tsmsdkv2 Typescript Definitions 
        run: cp ./types/* ./node_modules/@sepior/tsmsdkv2/

      - name: Run Tests
        run: npm test
        continue-on-error: true   # ToDo: remove once integration with hosted BV sandbox is in place.

      - name: Build TypeScript application
        run: npm run build

      - name: Publish to GitHub npm package registry
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: npm publish